openapi: 3.0.0
info:
  title: Game Lobby API
  version: 1.0.0
paths:
  /game/lobby:
    get:
      summary: Получение информации о лобби
      description: >
        Позволяет получить информацию о лобби по его идентификатору, при условии, что пользователь авторизован в этом лобби.
      parameters:
        - name: lobbyId
          in: query
          required: true
          schema:
            type: string
            description: Идентификатор лобби
        - name: playerId
          in: query
          required: true
          schema:
            type: string
            description: Идентификатор пользователя
      responses:
        '200':
          description: Успешное присоединение к лобби или создание нового
          content:
            application/json:
              schema:
                type: object
                properties:
                  lobbyId:
                    type: string
                    description: Идентификатор лобби
                  players:
                    type: array
                    $ref: 'components/players.yaml#/components/schemas/Players'
                  games: 
                    type: array
                    $ref: 'components/games.yaml#/components/schemas/Game'
                                    

        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                type: object
                $ref: 'components/errors.yaml#/components/schemas/Error'
        '401':
          description: Лобби не существует
          content:
            application/json:
              schema:
                type: object
                $ref: 'components/errors.yaml#/components/schemas/Error'        
        '404':
          description: Лобби не существует
          content:
            application/json:
              schema:
                type: object
                $ref: 'components/errors.yaml#/components/schemas/Error'